"use client";

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bh1WHgoIkIt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card"
import AddPerson from "@/components/AddPerson"

export function Dashboard() {
  return (
    <div className="min-h-screen bg-gray-100">
      <header className="bg-gray-800 text-white py-4">
        <div className="container mx-auto flex justify-center items-center">
          <h1 className="text-3xl font-bold">Where in the World</h1>
        </div>
      </header>
      <div className="container mx-auto py-6 px-6 md:px-0">
        <div className="flex justify-between mb-6 ml-6">
          <div className="flex space-x-4">
            <div className="flex">
              <Input
                type="text"
                placeholder="Search by Location"
                className="w-48 rounded-l-md rounded-r-none border-r-0 focus-visible:ring-0 focus-visible:ring-offset-0 focus-visible:border-gray-500"
              />
              <Button className="rounded-l-none rounded-r-md bg-gray-800 text-white hover:bg-gray-700 focus-visible:ring-0 focus-visible:ring-offset-0 focus-visible:border-gray-500">
                Search
              </Button>
            </div>
            <div className="flex">
              <Input
                type="text"
                placeholder="Search by People"
                className="w-48 rounded-l-md rounded-r-none border-r-0 focus-visible:ring-0 focus-visible:ring-offset-0 focus-visible:border-gray-500"
              />
              <Button className="rounded-l-none rounded-r-md bg-gray-800 text-white hover:bg-gray-700 focus-visible:ring-0 focus-visible:ring-offset-0 focus-visible:border-gray-500">
                Search
              </Button>
            </div>
          </div>
          <div className="mr-6">
            <AddPerson />
          </div>
        </div>
        <div className="flex gap-6">
          <div className="w-1/4 ml-6">
            <h2 className="text-xl font-bold mb-4">Starred People</h2>
            <div className="space-y-2">
              <Card className="p-4">
                <CardHeader>
                  <CardTitle>John Doe</CardTitle>
                  <CardDescription>Best Friend</CardDescription>
                </CardHeader>
                <CardContent>
                  <p>Lives in: New York</p>
                  <p>Visited: Paris, London, Tokyo</p>
                </CardContent>
              </Card>
              <Card className="p-4">
                <CardHeader>
                  <CardTitle>Jane Smith</CardTitle>
                  <CardDescription>Family</CardDescription>
                </CardHeader>
                <CardContent>
                  <p>Lives in: Los Angeles</p>
                  <p>Visited: Berlin, Rome, Sydney</p>
                </CardContent>
              </Card>
            </div>
          </div>
          <div className="w-3/4 mr-6">
            <h2 className="text-xl font-bold mb-4">Map</h2>
            <div className="bg-gray-200 h-[500px] flex items-center justify-center">
              <p>Map placeholder - Mapbox integration coming soon</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}